name: flutter_practice
description: A flutter practice project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.3
  retrofit: ^4.0.1
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.2
  logger: ^1.3.0
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  retrofit_generator: ^6.0.0+1
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true
  assets:
    - config/local.env