name: flutter_practice
description: A flutter practice project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.3
  retrofit: ^4.0.1
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.2
  logger: ^1.3.0
  webview_flutter: ^4.2.0
  provider: ^6.0.5
  get: ^4.0.0
  cached_network_image: ^3.2.3
  flutter_constraintlayout: ^1.6.3-stable
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  rxdart: ^0.27.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  retrofit_generator: ^6.0.0+1
  json_serializable: ^6.6.1
  mockito: ^5.4.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/error_no_connection.png
    - assets/images/error_loading_or_parsing.png

    - config/dev.env
    - config/stage.env
    - config/prod.env